from core.exceptions.app import AppError


class ProviderError(AppError):
    pass
